name: Proxies

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths:
      - 'kubernetes/charts/homeassistant-proxy/**'
      - 'kubernetes/charts/octoprint-proxy/**'
      - '.github/workflows/proxies.yaml'

jobs:
  deploy-proxies:
    name: Deploy Proxies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Connect to Kubernetes
        uses: ./.github/actions/connect-k8s
        with:
          kubeconfig: "${{ secrets.KUBECONFIG }}"
          hostname: kubernetes-api.${{ vars.HOST }}
          serviceTokenId: ${{ vars.CLOUDFLARE_TUNNEL_SERVICE_TOKEN_ID }}
          serviceTokenSecret: ${{ secrets.CLOUDFLARE_TUNNEL_SERVICE_TOKEN_SECRET }}

      - name: Install homeassistant-proxy
        run: |
          helm dependency update .
          helm upgrade --install --wait --atomic --debug \
            homeassistant-proxy . \
            --namespace default \
            -f values.yaml \
            --set ingress.host="homeassistant.${{ vars.HOST }}"
        working-directory: kubernetes/charts/homeassistant-proxy

      - name: Install octoprint-proxy
        run: |
          helm dependency update .
          helm upgrade --install --wait --atomic --debug \
            octoprint-proxy . \
            --namespace default \
            -f values.yaml \
            --set ingress.host="octoprint.${{ vars.HOST }}"
        working-directory: kubernetes/charts/octoprint-proxy

      - name: Disconnect from Kubernetes
        uses: ./.github/actions/disconnect-k8s