apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: teamspeak
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TS3SERVER_SERVERADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: serveradmin-password
            - name: TS3SERVER_DB_PLUGIN
              value: ts3db_sqlite3
            - name: TS3SERVER_DB_SQLCREATEPATH
              value: create_sqlite
            - name: TS3SERVER_LICENSE
              value: accept
            - name: TS3SERVER_FILETRANSFER_IP
              value: "0.0.0.0"
            - name: TS3SERVER_FILETRANSFER_PORT
              value: {{ required "ports.filetransfer is required" .Values.ports.filetransfer | quote }}
            - name: TS3SERVER_QUERY_PORT
              value: {{ required "ports.serverquery is required" .Values.ports.serverquery | quote }}
            - name: TS3SERVER_DEFAULT_VOICE_PORT
              value: {{ required "ports.voice is required" .Values.ports.voice | quote }}
            - name: TZ
              value: UTC
          ports:
            - name: filetransfer
              containerPort: {{ .Values.ports.filetransfer }}
              hostPort: {{ .Values.ports.filetransfer }}
              protocol: TCP
            - name: serverquery
              containerPort: {{ .Values.ports.serverquery }}
              hostPort: {{ .Values.ports.serverquery }}
              protocol: TCP
            - name: voice
              containerPort: {{ .Values.ports.voice }}
              hostPort: {{ .Values.ports.voice }}
              protocol: UDP
          volumeMounts:
            - name: data
              mountPath: /var/ts3server
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            tcpSocket:
              port: {{ .Values.ports.serverquery }}
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 10
            tcpSocket:
              port: {{ .Values.ports.serverquery }}
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 30
            initialDelaySeconds: 0
            periodSeconds: 5
            tcpSocket:
              port: {{ .Values.ports.serverquery }}
            timeoutSeconds: 1
          resources: {{ toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
      nodeSelector:
        kubernetes.io/arch: amd64