{
 "title": "Energy",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Battery State of Charge",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Battery SoC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "growatt_battery_state_of_charge"
      }
     ]
    }
   ]
  },
  {
   "title": "Solar Energy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "alias": "Solar Input",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kW",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "growatt_input_kilowatt_actual" }
     ]
    }
   ]
  },
  {
   "title": "Power output",
   "type": "timeseries",
   "description": "Includes both solar and battery output",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "alias": "Power output",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kW",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "growatt_output_kilowatt_actual" }
     ]
    }
   ]
  },
  {
   "title": "Import from grid",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "alias": "Import from grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kW",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "growatt_import_from_grid_actual"
      }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "kW",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "growatt_local_load_consumption_actual"
      }
     ]
    }
   ]
  },
  {
   "title": "Energy use per day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Energy use",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "query": "SELECT mean(\"value\") FROM \"kWh\" WHERE (\"entity_id\" = 'growatt_local_load_consumption_today') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "entity_id",
       "operator": "=",
       "value": "growatt_local_load_consumption_today"
      }
     ]
    }
   ]
  }
 ]
}