{
 "title": "Minecraft",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Server Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{container=\"minecraft\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Players (Current)",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "targets": [
    { "expr": "mc_player_list", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Player Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "count(mc_player_list)", "legendFormat": "Player Count" }
   ]
  },
  {
   "title": "Entities (Current)",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mc_entities_total) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Chunks Loaded per Dimension (Current)",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mc_dimension_chunks_loaded", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{container=\"minecraft\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"minecraft\"}[1m]))",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"minecraft\"})",
     "legendFormat": "Pod Memory"
    }
   ]
  },
  {
   "title": "Server Tick Duration (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(mc_server_tick_seconds_sum[1m]) / rate(mc_server_tick_seconds_count[1m])) by (name)",
     "legendFormat": "Tick Duration (Avg)"
    }
   ]
  },
  {
   "title": "Server Tick Duration (95th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.95, rate(mc_server_tick_seconds_bucket[1m]))) by (name)",
     "legendFormat": "Tick Duration (95th)"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(mc_entities_total) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Chunks Loaded per Dimension (Current)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "chunks" } },
   "targets": [
    {
     "expr": "sum(mc_dimension_chunks_loaded) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Dimension Tick Duration (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(mc_dimension_tick_seconds_sum[1m]) / rate(mc_dimension_tick_seconds_count[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Dimension Tick Duration (95th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.95, rate(mc_dimension_tick_seconds_bucket[1m]))) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "JVM Garbage Collection Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{gc=\"G1 Concurrent GC\"}[1m]))",
     "legendFormat": "G1 Concurrent GC"
    },
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{gc=\"G1 Old Generation\"}[1m]))",
     "legendFormat": "G1 Old Generation"
    },
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{gc=\"G1 Young Generation\"}[1m]))",
     "legendFormat": "G1 Young Generation"
    }
   ]
  },
  {
   "title": "JVM Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "targets": [
    {
     "expr": "sum(process_open_fds{container=\"minecraft\"})",
     "legendFormat": "Open FDs"
    },
    {
     "expr": "sum(process_max_fds{container=\"minecraft\"})",
     "legendFormat": "Max FDs"
    }
   ]
  },
  {
   "title": "JVM Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{area=\"heap\"})",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{area=\"heap\"})",
     "legendFormat": "Max Heap"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{area=\"heap\"})",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "JVM Non-Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{area=\"nonheap\"})",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "sum(jvm_memory_bytes_max{area=\"nonheap\"})",
     "legendFormat": "Max Heap"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{area=\"nonheap\"})",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(jvm_threads_current{container=\"minecraft\"})",
     "legendFormat": "Current Threads"
    },
    {
     "expr": "sum(jvm_threads_peak{container=\"minecraft\"})",
     "legendFormat": "Peak Threads"
    }
   ]
  },
  {
   "title": "JVM Classes Loaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "targets": [
    {
     "expr": "sum(jvm_classes_currently_loaded{container=\"minecraft\"})",
     "legendFormat": "Current Threads"
    }
   ]
  }
 ]
}